// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PublishRecognitionRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub recognition: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PublishRecognitionResponse {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
