// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartService {}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordMessage {
    #[prost(bytes = "vec", tag = "1")]
    pub metadata: ::prost::alloc::vec::Vec<u8>,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubmitMessage {
    #[prost(bytes = "vec", tag = "1")]
    pub metadata: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StopService {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Action {
    #[prost(oneof = "action::Kind", tags = "1, 2, 3, 4")]
    pub kind: ::core::option::Option<action::Kind>,
}
/// Nested message and enum types in `Action`.
pub mod action {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        StartService(super::StartService),
        #[prost(message, tag = "2")]
        RecordMessage(super::RecordMessage),
        #[prost(message, tag = "3")]
        SubmitMessage(super::SubmitMessage),
        #[prost(message, tag = "4")]
        StopService(super::StopService),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMessageRequest {
    #[prost(string, tag = "1")]
    pub number: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMessageResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub message: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCatalogRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCatalogResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub catalog: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogResponse {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
